#!/bin/bash

backup_filename=$(ls -t ${project_folder}/tmp/database_backups/production_*.dump | head -n 1)
mcio_database_name="mcio_development"

echo "===> Killing all active connections to the database..."
psql -h localhost -U root -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '"$mcio_database_name"' AND pid <> pg_backend_pid();"

echo "===> Restoring $backup_filename ..."

pg_restore --verbose --clean --if-exists --no-acl --no-owner --role=root -U root -h localhost -d $mcio_database_name "$backup_filename"

echo "===> Updating ar_internal_metadata ..."
psql -h localhost -U root -d $mcio_database_name -c "UPDATE ar_internal_metadata SET value='development' WHERE key='environment';"

echo "===> Updating last user email and password to avoid conflicts with production user..."

new_user_email=dwight_schrute@dundermifflin.com
new_password=beets

bin/rails runner "User.last.update_columns(email_address: \"${new_user_email}\", password_digest: BCrypt::Password.create(\"${new_password}\"))"

echo "===> Done!"
