#!/bin/bash

set -eo pipefail

run_dev=false
database=missing___database

for arg in "$@"; do
  if [[ "$arg" == "--rundev" ]] || [[ "$arg" == "-r" ]]; then
    run_dev=true
    continue
  fi

  if [[ "$arg" == "--database="* ]] || [[ "$arg" == "-d="* ]]; then
    database="${arg#*=}"
    continue
  fi
done

if [ "$database" = "missing___database" ]; then
  echo "Error: Please provide the RAILS (not heroku) database name using --database=NAME or -d=NAME. Example: --database=PRIMARY"
  exit 1
fi

heroku_database="MCIO_${database^^}_DATABASE"

backup_filename=$(ls -t ${project_folder}/tmp/database_backups/production_${database}_*.dump | head -n 1)
mcio_database_name="mcio_${database}"

echo "===> Killing all active connections to the database..."
psql -h localhost -U root -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '"$mcio_database_name"' AND pid <> pg_backend_pid();"

echo "===> Restoring $backup_filename ..."

pg_restore --verbose --clean --if-exists --no-acl --no-owner --role=root -U root -h localhost -d $mcio_database_name "$backup_filename"

echo "===> Updating ar_internal_metadata ..."
psql -h localhost -U root -d $mcio_database_name -c "UPDATE ar_internal_metadata SET value='development' WHERE key='environment';"

if [[ "$database" == "primary" ]]; then
  echo "===> Updating last user email and password to avoid conflicts with production user..."

  new_user_email=dwight_schrute@dundermifflin.com
  new_password=beets

  bin/rails runner "User.last.update_columns(email_address: \"${new_user_email}\", password_digest: BCrypt::Password.create(\"${new_password}\"))"
fi;

echo "===> Done!"

if [ "$run_dev" = true ]; then
  echo "===> Starting bin/dev..."
  bin/dev
fi
