#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 <production-backup-name>"
  echo "Example: $0 b001"
  exit 1
fi

bkp_name=$1

echo "===> Obtaining the database name to restore into staging ..."
cmd="heroku pg:backups:info ${bkp_name} --app mcio-production | grep 'Database:' | awk '{print \$2}'"
echo "Running command: $cmd"
database_name="$(eval $cmd)"
database_url="${database_name}_URL"

echo "===> Obtaining the backup_url from production ..."
cmd="heroku pg:backups:url ${bkp_name} --app mcio-production"
echo "Running command: $cmd"
backup_url="$(eval $cmd)"

echo "===> Restoring production backup ${bkp_name} (${database_name}) into ${database_name} in staging..."

cmd="heroku pg:backups:restore \"${backup_url}\" ${database_url} --app mcio-staging --confirm mcio-staging"
echo "Running command: $cmd"
eval $cmd

if [ $? -ne 0 ]; then
  echo "Error: Failed to restore the backup."
  exit 1
fi

echo "===> Updating ar_internal_metadata ..."
heroku pg:psql ${database_url} --app mcio-staging -c "UPDATE ar_internal_metadata SET value='staging' WHERE key='environment';"

if [[ "$database_name" == "MCIO_PRIMARY_DATABASE" ]]; then
  echo "===> Running command to update user credentials..."

  new_user_email="me+mcio_staging@saulo.pro"
  new_password="8udmfo6TR223gzyrpwHP"

  heroku run --app mcio-staging -- rails runner "User.last.update_columns(email_address: \"${new_user_email}\", password_digest: BCrypt::Password.create(\"${new_password}\"))"
fi;

echo "===> Done!"
