#!/bin/bash

run_dev=false
database=missing___database

for arg in "$@"; do
  if [[ "$arg" == "--rundev" ]] || [[ "$arg" == "-r" ]]; then
    run_dev=true
    continue
  fi

  if [[ "$arg" == "--database="* ]] || [[ "$arg" == "-d="* ]]; then
    database="${arg#*=}"
    continue
  fi
done

if [ "$database" = "missing___database" ]; then
  echo "Error: Please provide the RAILS (not heroku) database name using --database=NAME or -d=NAME. Example: --database=primary"
  exit 1
fi

heroku_database="MCIO_${database^^}_DATABASE"

echo "===> Backing up Heroku ${heroku_database} production database..."
heroku pg:backups:capture $heroku_database --app mcio-production

echo "===> Downloading the backup locally..."
backup_filename="${project_folder}/tmp/database_backups/production_${database}_$(date +%Y%m%d_%H%M%S).dump"
heroku pg:backups:download --app mcio-production --output="${backup_filename}"

if [ "$run_dev" = true ]; then
  source "${project_folder}/.devcontainer/scripts/cli/db_restore_last_dump_in_local" --database=$database --dev
else
  source "${project_folder}/.devcontainer/scripts/cli/db_restore_last_dump_in_local" --database=$database
fi
